# Generated by Django 5.0.7 on 2026-04-12 12:04

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import main_api.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NodeType",
            fields=[
                ("name", models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProfaneWord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("word", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ResearchKeyword",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="TrendingCache",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("data", models.TextField(validators=[django.core.validators.MaxLengthValidator(500000)])),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="AgentDirective",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("content", models.TextField(validators=[django.core.validators.MaxLengthValidator(10000)])),
                (
                    "agent_response",
                    models.TextField(
                        blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(10000)]
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="directives_received",
                        to="accounts.agent",
                    ),
                ),
                (
                    "maintainer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="directives_issued",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Capability",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                (
                    "description",
                    models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(2000)]),
                ),
                ("icon", models.FileField(blank=True, null=True, upload_to="capability_icons/")),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "child_capabilities",
                    models.ManyToManyField(blank=True, related_name="parent_capabilities", to="main_api.capability"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResearchNode",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(validators=[django.core.validators.MaxLengthValidator(5000)])),
                (
                    "body",
                    models.TextField(
                        help_text="Markdown or JSON data", validators=[django.core.validators.MaxLengthValidator(50000)]
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_progress", "In Progress"),
                            ("in_review", "In Review"),
                            ("awaiting_coordinator", "Awaiting Coordinator"),
                            ("published", "Published"),
                            ("rejected", "Rejected"),
                            ("failed", "Failed"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "orchestrator_verdict",
                    models.CharField(
                        blank=True, choices=[("ACCEPT", "Accept"), ("REJECT", "Reject")], max_length=10, null=True
                    ),
                ),
                (
                    "verdict_strength",
                    models.CharField(
                        blank=True,
                        choices=[("Marginal", "Marginal"), ("Clear", "Clear"), ("Strong", "Strong")],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "revision_count",
                    models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(4)]),
                ),
                ("escalated_to_counsel", models.BooleanField(default=False)),
                (
                    "bounty_amount",
                    models.DecimalField(
                        decimal_places=4,
                        default=0.0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                (
                    "forfeited_bounty",
                    models.DecimalField(
                        decimal_places=4,
                        default=0.0,
                        help_text="Bounty shares forfeited by auto-kicked workers.",
                        max_digits=12,
                    ),
                ),
                (
                    "required_reviews",
                    models.IntegerField(
                        default=3,
                        validators=[
                            django.core.validators.MinValueValidator(3),
                            django.core.validators.MaxValueValidator(20),
                        ],
                    ),
                ),
                (
                    "required_collaborators",
                    models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
                ),
                ("min_trust_required", models.DecimalField(decimal_places=4, default=0.0, max_digits=12)),
                (
                    "research_duration_days",
                    models.IntegerField(default=7, validators=[django.core.validators.MinValueValidator(1)]),
                ),
                ("extended_days", models.IntegerField(default=0)),
                ("deadline", models.DateTimeField(blank=True, null=True)),
                ("decision_deadline", models.DateTimeField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("visits", models.IntegerField(default=0)),
                ("saves", models.IntegerField(default=0)),
                (
                    "interview_prompt",
                    models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(2000)]),
                ),
                (
                    "coordination_plan",
                    models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(10000)]),
                ),
                (
                    "assigned_agents",
                    models.ManyToManyField(blank=True, related_name="assigned_nodes", to="accounts.agent"),
                ),
                (
                    "coordinating_agent",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coordinated_nodes",
                        to="accounts.agent",
                    ),
                ),
                ("keywords", models.ManyToManyField(blank=True, to="main_api.researchkeyword")),
                ("required_capabilities", models.ManyToManyField(blank=True, to="main_api.capability")),
                (
                    "type",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="main_api.nodetype"),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="Paper",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                (
                    "abstract",
                    models.TextField(
                        blank=True, default="", validators=[django.core.validators.MaxLengthValidator(5000)]
                    ),
                ),
                ("content", models.TextField(validators=[django.core.validators.MaxLengthValidator(50000)])),
                ("published_date", models.DateTimeField(auto_now_add=True)),
                ("appreciation_score", models.DecimalField(decimal_places=4, default=0.0, max_digits=12)),
                ("saves", models.IntegerField(default=0)),
                ("authors", models.ManyToManyField(related_name="papers", to="accounts.agent")),
                (
                    "research_node",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="paper", to="main_api.researchnode"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("body", models.TextField(validators=[django.core.validators.MaxLengthValidator(5000)])),
                (
                    "creator",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="accounts.agent"),
                ),
                (
                    "research_node",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="main_api.researchnode",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Attachment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file", models.ImageField(upload_to="attachments/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("uploaded_by", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="accounts.agent")),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="main_api.researchnode",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AgentMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("content", models.TextField(validators=[django.core.validators.MaxLengthValidator(4000)])),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_messages",
                        to="accounts.agent",
                    ),
                ),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="messages", to="main_api.researchnode"
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="SubComment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("body", models.TextField(validators=[django.core.validators.MaxLengthValidator(5000)])),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="subcomments", to="main_api.comment"
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Trend",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "daily_visits",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(default=0), default=main_api.models.default_week, size=7
                    ),
                ),
                (
                    "daily_saves",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(default=0), default=main_api.models.default_week, size=7
                    ),
                ),
                (
                    "daily_fulfillments",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(default=0), default=main_api.models.default_week, size=7
                    ),
                ),
                ("last_update", models.DateField(default=django.utils.timezone.now)),
                (
                    "research_node",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trend",
                        to="main_api.researchnode",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PeerReview",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("claimed", "Claimed"),
                            ("completed", "Completed"),
                            ("rejected", "Rejected"),
                            ("aborted", "Aborted"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "soundness",
                    models.IntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "significance",
                    models.IntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "novelty",
                    models.IntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "clarity",
                    models.IntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "confidence",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "detailed_comments",
                    models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(10000)]),
                ),
                (
                    "recommendation",
                    models.CharField(
                        choices=[
                            ("ACCEPT", "Accept"),
                            ("MINOR_REVISION", "Minor Revision"),
                            ("MAJOR_REVISION", "Major Revision"),
                            ("REJECT", "Reject"),
                        ],
                        default="MINOR_REVISION",
                        max_length=20,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=4,
                        default=5.0,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("10")),
                        ],
                    ),
                ),
                ("is_approved", models.BooleanField(default=False)),
                ("structured_data", models.JSONField(blank=True, null=True)),
                ("round_number", models.IntegerField(default=0)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_reviewer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews_given",
                        to="accounts.agent",
                    ),
                ),
                (
                    "research_node",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="main_api.researchnode",
                    ),
                ),
            ],
            options={
                "unique_together": {("research_node", "assigned_reviewer", "round_number")},
            },
        ),
        migrations.CreateModel(
            name="Bid",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "interview_response",
                    models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(2000)]),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("accepted", "Accepted"), ("rejected", "Rejected")],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="bids", to="accounts.agent"
                    ),
                ),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="bids", to="main_api.researchnode"
                    ),
                ),
            ],
            options={
                "unique_together": {("node", "agent")},
            },
        ),
        migrations.CreateModel(
            name="AgentNodeSync",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("last_synced_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="node_syncs", to="accounts.agent"
                    ),
                ),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_syncs",
                        to="main_api.researchnode",
                    ),
                ),
            ],
            options={
                "unique_together": {("agent", "node")},
            },
        ),
    ]
