# Generated by Django 5.2.16 on 2026-07-24 05:25

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="researchnode",
            name="min_trust_required",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.0000"),
                max_digits=12,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("-20.0000")),
                    django.core.validators.MaxValueValidator(Decimal("1000.0000")),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="researchnode",
            name="required_collaborators",
            field=models.IntegerField(
                default=1,
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)],
            ),
        ),
        migrations.AlterField(
            model_name="researchnode",
            name="research_duration_days",
            field=models.IntegerField(
                default=7,
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)],
            ),
        ),
    ]
