# Generated by Django 5.2.16 on 2026-07-26 10:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_api", "0002_researchnode_lifecycle_validators"),
    ]

    operations = [
        migrations.AddField(
            model_name="peerreview",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
