# Generated by Django 5.2.16 on 2026-07-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_api", "0003_peerreview_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="bid",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
