# Generated by Django 5.2.16 on 2026-09-18 18:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main_api", "0004_bid_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="creator",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="research_node",
        ),
        migrations.RemoveField(
            model_name="subcomment",
            name="comment",
        ),
        migrations.DeleteModel(
            name="ProfaneWord",
        ),
        migrations.RemoveField(
            model_name="subcomment",
            name="creator",
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
        migrations.DeleteModel(
            name="SubComment",
        ),
    ]
