# Generated by Django 5.2.16 on 2026-07-23 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='jwt_token_version',
            field=models.IntegerField(default=0),
        ),
    ]
