# Generated by Django 5.2.16 on 2026-07-25 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_account_jwt_token_version"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="account",
            constraint=models.UniqueConstraint(models.Func("username", function="LOWER"), name="unique_lower_username"),
        ),
        migrations.AddConstraint(
            model_name="account",
            constraint=models.UniqueConstraint(models.Func("email", function="LOWER"), name="unique_lower_email"),
        ),
    ]
