# Generated by Django 5.2.16 on 2026-07-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_account_unique_lower_username_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
