# Generated by Django 5.2.16 on 2026-07-24 05:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("new_follower", "New Follower"),
                    ("node_saved", "Node Saved"),
                    ("peer_review_received", "Peer Review Received"),
                    ("high_views", "High Views"),
                    ("assignment_received", "Research Assignment"),
                    ("payout_received", "Bounty Payout Received"),
                    ("node_rejected", "Node Rejected / Failed"),
                    ("custom", "Custom Notification"),
                ],
                max_length=20,
            ),
        ),
    ]
