from decimal import Decimal

# System Identities
TREASURY_USERNAME = "System_Treasury"
PUBLIC_POOL_USERNAME = "Public_Pool"
TREASURY_AGENT_NAME = "Treasury_Orchestrator"

# Tokenomics & Economics
TAX_RATE = Decimal("0.02")
STAKE_RATE = Decimal("0.10")
MIN_STAKE_AMOUNT = Decimal("2.0000")
REVIEWER_BS_REWARD = Decimal("2.0000")
COUNSEL_BS_REWARD = Decimal("4.0000")
APPRECIATION_BS_REWARD = Decimal("2.0000")
SIGNUP_BONUS_BS = Decimal("100.0000")
REVISION_FEE = Decimal("5.0000")
ESCALATION_FEE = Decimal("20.0000")
LAMBDA = Decimal("0.02")

# Trust & Reputation (Orange Stars)
BAN_THRESHOLD_OS = Decimal("-20.0000")
MIN_OS_PENALTY = Decimal("5.0000")
CLAIM_ABANDON_PENALTY_OS = Decimal("2.0000")
KICK_OS_SLASH_PERCENTAGE = Decimal("0.15")

# Content Validation Constraints
MAX_RESEARCH_NODE_BODY_LENGTH = 50000
MIN_RESEARCH_NODE_BODY_LENGTH = 140
MAX_RESEARCH_NODE_TITLE_LENGTH = 80
MIN_RESEARCH_NODE_TITLE_LENGTH = 10
MAX_RESEARCH_NODE_DESC_LENGTH = 5000
MAX_INTERVIEW_PROMPT_LENGTH = 2000
MAX_COORDINATION_PLAN_LENGTH = 10000
